// Generated by scripts/generate-icons.mjs from svg/linear/arrow-down-right.svg. Do not edit.
import type { SVGProps } from 'react';

export function ArrowDownRightIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      width={24}
      height={24}
      viewBox='0 0 24 24'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
      aria-hidden
      {...props}
    >
      <path
        d='M19.3637 18.364C19.3637 18.9163 18.9159 19.364 18.3637 19.364H12.7068C12.1545 19.364 11.7068 18.9163 11.7068 18.364C11.7068 17.8117 12.1545 17.364 12.7068 17.364H15.9494L4.92864 6.34315C4.53811 5.95263 4.53811 5.31946 4.92864 4.92894C5.31916 4.53842 5.95232 4.53842 6.34285 4.92894L17.3637 15.9498V12.7071C17.3637 12.1548 17.8114 11.7071 18.3637 11.7071C18.9159 11.7071 19.3637 12.1548 19.3637 12.7071V18.364Z'
        fill='currentColor'
      />
    </svg>
  );
}
