// Generated by scripts/generate-icons.mjs from svg/linear/arrow-down-left.svg. Do not edit.
import type { SVGProps } from 'react';

export function ArrowDownLeftIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      width={24}
      height={24}
      viewBox='0 0 24 24'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
      aria-hidden
      {...props}
    >
      <path
        d='M4.63574 18.364C4.63574 18.9163 5.08346 19.364 5.63574 19.364H11.2926C11.8449 19.364 12.2926 18.9163 12.2926 18.364C12.2926 17.8117 11.8449 17.364 11.2926 17.364H8.04996L19.0708 6.34315C19.4613 5.95263 19.4613 5.31946 19.0708 4.92894C18.6802 4.53842 18.0471 4.53842 17.6566 4.92894L6.63574 15.9498L6.63574 12.7071C6.63574 12.1548 6.18803 11.7071 5.63574 11.7071C5.08346 11.7071 4.63574 12.1548 4.63574 12.7071V18.364Z'
        fill='currentColor'
      />
    </svg>
  );
}
