// Generated by scripts/generate-icons.mjs from svg/linear/bluetooth.svg. Do not edit.
import type { SVGProps } from 'react';

export function BluetoothIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      width={24}
      height={24}
      viewBox='0 0 24 24'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
      aria-hidden
      {...props}
    >
      <path
        fillRule='evenodd'
        clipRule='evenodd'
        d='M13.1094 4.20444C11.7803 3.31836 10 4.27115 10 5.86854V9.91939L7.62473 8.01915C7.19347 7.67414 6.56418 7.74406 6.21917 8.17532C5.87416 8.60659 5.94408 9.23588 6.37534 9.58089L9.39926 12L6.37534 14.4192C5.94408 14.7642 5.87416 15.3935 6.21917 15.8247C6.56418 16.256 7.19347 16.3259 7.62473 15.9809L10 14.0806V18.1315C10 19.7289 11.7803 20.6817 13.1094 19.7956L16.3067 17.6641C17.4941 16.8725 17.4941 15.1276 16.3067 14.3359L12.8028 12L16.3067 9.66412C17.4941 8.87248 17.4941 7.12756 16.3067 6.33592L13.1094 4.20444ZM15.1973 8.00002L12 10.1315V5.86854L15.1973 8.00002ZM15.1973 16L12 18.1315V13.8685L15.1973 16Z'
        fill='currentColor'
      />
    </svg>
  );
}
