// Generated by scripts/generate-icons.mjs from svg/linear/bold.svg. Do not edit.
import type { SVGProps } from 'react';

export function BoldIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      width={24}
      height={24}
      viewBox='0 0 24 24'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
      aria-hidden
      {...props}
    >
      <path
        d='M14.5 21H5.13861C5.06206 21 5 20.9379 5 20.8614L5.00001 12H14.5C16.9853 12 19 14.0147 19 16.5C19 18.9853 16.9853 21 14.5 21Z'
        stroke='currentColor'
        strokeWidth='2'
        strokeLinecap='round'
        strokeLinejoin='round'
      />
      <path
        d='M13.5 12H5.12871C5.05763 12 5 11.9424 5 11.8713L5.00001 3H13.5C15.9853 3 18 5.01472 18 7.5C18 9.98528 15.9853 12 13.5 12Z'
        stroke='currentColor'
        strokeWidth='2'
        strokeLinecap='round'
        strokeLinejoin='round'
      />
    </svg>
  );
}
