// Generated by scripts/generate-icons.mjs from svg/linear/check.svg. Do not edit.
import type { SVGProps } from 'react';

export function CheckIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      width={24}
      height={24}
      viewBox='0 0 24 24'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
      aria-hidden
      {...props}
    >
      <path
        fillRule='evenodd'
        clipRule='evenodd'
        d='M19.3132 5.77332C19.7146 5.39416 20.347 5.41201 20.7263 5.81336C21.1051 6.21484 21.0875 6.84732 20.6862 7.22645L9.03973 18.2264C8.65444 18.5903 8.05209 18.5901 7.66669 18.2264L3.31317 14.1151C2.91168 13.7359 2.89396 13.1026 3.27313 12.7011C3.65236 12.3001 4.28486 12.2821 4.68622 12.661L8.35321 16.1239L19.3132 5.77332Z'
        fill='currentColor'
      />
    </svg>
  );
}
