// Generated by scripts/generate-icons.mjs from svg/linear/coins-02.svg. Do not edit.
import type { SVGProps } from 'react';

export function Coins02Icon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      width={24}
      height={24}
      viewBox='0 0 16 16'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
      aria-hidden
      {...props}
    >
      <path
        d='M9.33333 11.9997C12.2789 11.9997 14.6667 9.61187 14.6667 6.66634C14.6667 3.72082 12.2789 1.33301 9.33333 1.33301C6.38781 1.33301 4 3.72082 4 6.66634C4 9.61187 6.38781 11.9997 9.33333 11.9997Z'
        stroke='currentColor'
        strokeWidth='1.5'
        strokeLinecap='round'
      />
      <path
        d='M8.7781 13.9789C8.04216 14.4155 7.18296 14.6663 6.26516 14.6663C3.54148 14.6663 1.3335 12.4583 1.3335 9.73461C1.3335 8.81681 1.58421 7.95761 2.02088 7.22168'
        stroke='currentColor'
        strokeWidth='1.5'
        strokeLinecap='round'
      />
    </svg>
  );
}
