// Generated by scripts/generate-icons.mjs from svg/bold/copy.svg. Do not edit.
import type { SVGProps } from 'react';

export function CopyBoldIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      width={24}
      height={24}
      viewBox='0 0 24 24'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
      aria-hidden
      {...props}
    >
      <g>
        <path
          d='M18 15C19.6569 15 21 13.6569 21 12V6C21 4.34315 19.6569 3 18 3H14C12.3431 3 11 4.34315 11 6V7.7H11.5C13.1569 7.7 14.5 9.04315 14.5 10.7V15H18Z'
          fill='currentColor'
        />
        <path
          d='M6 9C4.34315 9 3 10.3431 3 12V18C3 19.6569 4.34315 21 6 21H10C11.6569 21 13 19.6569 13 18V12C13 10.3431 11.6569 9 10 9H6Z'
          fill='currentColor'
        />
      </g>
    </svg>
  );
}
