// Generated by scripts/generate-icons.mjs from svg/bold/credit.svg. Do not edit.
import type { SVGProps } from 'react';

export function CreditBoldIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      width={24}
      height={24}
      viewBox='0 0 24 24'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
      aria-hidden
      {...props}
    >
      <g clipPath='url(#clip0_4279_55112)'>
        <path
          fillRule='evenodd'
          clipRule='evenodd'
          d='M12 -0.00195312C18.6274 -0.00195312 24 5.37062 24 11.998C24 18.6255 18.6274 23.998 12 23.998C5.37257 23.998 0 18.6255 0 11.998C0 5.37062 5.37257 -0.00195312 12 -0.00195312ZM12 2.25219C17.3825 2.25219 21.7459 6.61555 21.7459 11.998C21.7459 17.3805 17.3825 21.7439 12 21.7439C6.61751 21.7439 2.25414 17.3805 2.25414 11.998C2.25414 6.61555 6.61751 2.25219 12 2.25219Z'
          fill='currentColor'
        />
        <path
          fillRule='evenodd'
          clipRule='evenodd'
          d='M11.9998 2.25244C17.3823 2.25244 21.7456 6.61581 21.7456 11.9983C21.7456 17.3808 17.3823 21.7442 11.9998 21.7442C6.61727 21.7442 2.25391 17.3808 2.25391 11.9983C2.25391 6.61581 6.61727 2.25244 11.9998 2.25244ZM8.22075 8.21929H15.7788V15.7773H8.22075V8.21929Z'
          fill='currentColor'
        />
      </g>
      <defs>
        <linearGradient
          x1='18.0029'
          y1='41.9632'
          x2='5.91287'
          y2='41.4114'
          gradientUnits='userSpaceOnUse'
        >
          <stop stop-color='#A7F950' />
          <stop offset='1' stop-color='#3AE6B2' />
        </linearGradient>
        <clipPath></clipPath>
      </defs>
    </svg>
  );
}
