// Generated by scripts/generate-icons.mjs from svg/linear/hashtag.svg. Do not edit.
import type { SVGProps } from 'react';

export function HashtagIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      width={24}
      height={24}
      viewBox='0 0 24 24'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
      aria-hidden
      {...props}
    >
      <path
        d='M6.00034 21L9.00034 3.00002M15.0003 21L18.0003 3.00001M4.00034 8.00002L21.0003 8.00002M3.00032 16L20.0003 16'
        stroke='currentColor'
        strokeWidth='2'
        strokeLinecap='round'
        strokeLinejoin='round'
      />
    </svg>
  );
}
