// Generated by scripts/generate-icons.mjs from svg/bold/hashtag.svg. Do not edit.
import type { SVGProps } from 'react';

export function HashtagBoldIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      width={24}
      height={24}
      viewBox='0 0 24 24'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
      aria-hidden
      {...props}
    >
      <path
        d='M6.00034 20.9999L9.00034 2.99989M15.0003 20.9999L18.0003 2.99989M4.00034 7.99989L21.0003 7.99989M3.00032 15.9999L20.0003 15.9999'
        stroke='currentColor'
        strokeWidth='2'
        strokeLinecap='round'
        strokeLinejoin='round'
      />
    </svg>
  );
}
