// Generated by scripts/generate-icons.mjs from svg/bold/heading.svg. Do not edit.
import type { SVGProps } from 'react';

export function HeadingBoldIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      width={24}
      height={24}
      viewBox='0 0 24 24'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
      aria-hidden
      {...props}
    >
      <path
        d='M5.6 3V12M5.6 21V12M18.4 21V12M18.4 3V12M18.4 12H5.6M7.2 3H4M20 3H16.8M7.2 21H4M19.6 21H16.4'
        stroke='currentColor'
        strokeWidth='2'
        strokeLinecap='round'
        strokeLinejoin='round'
      />
    </svg>
  );
}
