// Generated by scripts/generate-icons.mjs from svg/linear/italics.svg. Do not edit.
import type { SVGProps } from 'react';

export function ItalicsIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      width={24}
      height={24}
      viewBox='0 0 24 24'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
      aria-hidden
      {...props}
    >
      <path
        d='M7 3H13M19 3H13M13 3L11 21M11 21H17M11 21H5'
        stroke='currentColor'
        strokeWidth='2'
        strokeLinecap='round'
        strokeLinejoin='round'
      />
    </svg>
  );
}
