// Generated by scripts/generate-icons.mjs from svg/bold/list.svg. Do not edit.
import type { SVGProps } from 'react';

export function ListBoldIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      width={24}
      height={24}
      viewBox='0 0 24 24'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
      aria-hidden
      {...props}
    >
      <path
        d='M21.5 4H7.5'
        stroke='currentColor'
        strokeWidth='2'
        strokeLinecap='round'
        strokeLinejoin='round'
      />
      <path
        d='M21.5 12H7.5'
        stroke='currentColor'
        strokeWidth='2'
        strokeLinecap='round'
        strokeLinejoin='round'
      />
      <path
        d='M21.5 20H7.5'
        stroke='currentColor'
        strokeWidth='2'
        strokeLinecap='round'
        strokeLinejoin='round'
      />
      <circle
        cx='1.25'
        cy='1.25'
        r='1.25'
        transform='matrix(-1 0 0 1 4.5 2.75)'
        fill='currentColor'
      />
      <circle
        cx='1.25'
        cy='1.25'
        r='1.25'
        transform='matrix(-1 0 0 1 4.5 10.75)'
        fill='currentColor'
      />
      <circle
        cx='1.25'
        cy='1.25'
        r='1.25'
        transform='matrix(-1 0 0 1 4.5 18.75)'
        fill='currentColor'
      />
    </svg>
  );
}
