// Generated by scripts/generate-icons.mjs from svg/bold/loudspeaker.svg. Do not edit.
import type { SVGProps } from 'react';

export function LoudspeakerBoldIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      width={24}
      height={24}
      viewBox='0 0 24 24'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
      aria-hidden
      {...props}
    >
      <g>
        <path
          d='M20.8286 2.95993C21.1548 2.8409 21.5 3.08241 21.5 3.42964V15.5708C21.5 15.918 21.1548 16.1595 20.8286 16.0405L13.7308 13.4504V5.55002L20.8286 2.95993Z'
          fill='currentColor'
        />
        <path
          d='M12.7308 5.74085V13.2596L5.80511 12.718C4.50395 12.6163 3.5 11.5308 3.5 10.2257V8.77479C3.5 7.46967 4.50395 6.38415 5.80511 6.2824L12.7308 5.74085Z'
          fill='currentColor'
        />
        <path
          d='M8.29464 20.1876L7.56613 13.8588L10.5522 14.0923L11.2388 19.8423C11.3441 20.7243 10.6553 21.5002 9.76707 21.5002C9.01408 21.5002 8.38075 20.9356 8.29464 20.1876Z'
          fill='currentColor'
        />
      </g>
    </svg>
  );
}
