// Generated by scripts/generate-icons.mjs from svg/linear/navigation.svg. Do not edit.
import type { SVGProps } from 'react';

export function NavigationIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      width={24}
      height={24}
      viewBox='0 0 24 24'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
      aria-hidden
      {...props}
    >
      <path
        fillRule='evenodd'
        clipRule='evenodd'
        d='M9.71944 4.62877C10.6039 2.6637 13.3953 2.66387 14.28 4.62877L20.5544 18.5731C21.4356 20.5323 19.5983 22.6169 17.5437 21.9891L12.1462 20.3397C12.0511 20.3107 11.9483 20.3106 11.8532 20.3397L6.45576 21.9891C4.40123 22.6167 2.56384 20.5322 3.44502 18.5731L9.71944 4.62877ZM12.4558 5.45006C12.2787 5.05723 11.7205 5.05707 11.5437 5.45006L5.26924 19.3934C5.093 19.7851 5.46014 20.2019 5.8708 20.077L11.2692 18.4276C11.7453 18.2821 12.2541 18.2822 12.7302 18.4276L18.1286 20.077C18.5394 20.2021 18.9064 19.7851 18.7302 19.3934L12.4558 5.45006Z'
        fill='currentColor'
      />
    </svg>
  );
}
