// Generated by scripts/generate-icons.mjs from svg/bold/paragraph-spacing.svg. Do not edit.
import type { SVGProps } from 'react';

export function ParagraphSpacingBoldIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      width={24}
      height={24}
      viewBox='0 0 24 24'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
      aria-hidden
      {...props}
    >
      <path
        d='M3 3.5H21'
        stroke='currentColor'
        strokeWidth='2'
        strokeLinecap='round'
        strokeLinejoin='round'
      />
      <path
        d='M3 20.5H21'
        stroke='currentColor'
        strokeWidth='2'
        strokeLinecap='round'
        strokeLinejoin='round'
      />
      <path
        d='M17 18L15 13.2L12.1846 6.44308C12.1162 6.27897 11.8838 6.27897 11.8154 6.44308L9 13.2L7 18M15 13.2H9'
        stroke='currentColor'
        strokeWidth='2'
        strokeLinecap='round'
        strokeLinejoin='round'
      />
    </svg>
  );
}
