// Generated by scripts/generate-icons.mjs from svg/linear/radio-selected.svg. Do not edit.
import type { SVGProps } from 'react';

export function RadioSelectedIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      width={24}
      height={24}
      viewBox='0 0 24 24'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
      aria-hidden
      {...props}
    >
      <g>
        <circle cx='12' cy='12' r='9' stroke='currentColor' strokeWidth='2' />
        <circle cx='12' cy='12' r='5' stroke='currentColor' strokeWidth='2' />
      </g>
    </svg>
  );
}
