// Generated by scripts/generate-icons.mjs from svg/bold/strikethrough.svg. Do not edit.
import type { SVGProps } from 'react';

export function StrikethroughBoldIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      width={24}
      height={24}
      viewBox='0 0 24 24'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
      aria-hidden
      {...props}
    >
      <path
        d='M18 3H9.5C7.01472 3 5 5.01472 5 7.5C5 7.95427 5.06731 8.39283 5.19251 8.80623M13.5 12C15.9853 12 18 14.0147 18 16.5C18 18.9853 15.9853 21 13.5 21H5'
        stroke='currentColor'
        strokeWidth='2'
        strokeLinecap='round'
        strokeLinejoin='round'
      />
      <path
        d='M3 12H21'
        stroke='currentColor'
        strokeWidth='2'
        strokeLinecap='round'
        strokeLinejoin='round'
      />
    </svg>
  );
}
