// Generated by scripts/generate-icons.mjs from svg/linear/subscript.svg. Do not edit.
import type { SVGProps } from 'react';

export function SubscriptIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      width={24}
      height={24}
      viewBox='0 0 24 24'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
      aria-hidden
      {...props}
    >
      <path
        d='M3 5.00002L8.60576 13.1538M8.60576 13.1538L14 21M8.60576 13.1538L14 5M8.60576 13.1538L3.41507 21'
        stroke='currentColor'
        strokeWidth='2'
        strokeLinecap='round'
        strokeLinejoin='round'
      />
      <path
        d='M17 21V19C17 17.8954 17.8954 17 19 17C20.1046 17 21 17.8954 21 19V21'
        stroke='currentColor'
        strokeWidth='2'
        strokeLinecap='round'
        strokeLinejoin='round'
      />
    </svg>
  );
}
