// Generated by scripts/generate-icons.mjs from svg/bold/superscript.svg. Do not edit.
import type { SVGProps } from 'react';

export function SuperscriptBoldIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      width={24}
      height={24}
      viewBox='0 0 24 24'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
      aria-hidden
      {...props}
    >
      <path
        d='M3 5.00002L8.60576 13.1538M8.60576 13.1538L14 21M8.60576 13.1538L14 5M8.60576 13.1538L3.41507 21'
        stroke='currentColor'
        strokeWidth='2'
        strokeLinecap='round'
        strokeLinejoin='round'
      />
      <path
        d='M17 7V5C17 3.89543 17.8954 3 19 3C20.1046 3 21 3.89543 21 5V7'
        stroke='currentColor'
        strokeWidth='2'
        strokeLinecap='round'
        strokeLinejoin='round'
      />
    </svg>
  );
}
