// Generated by scripts/generate-icons.mjs from svg/bold/text.svg. Do not edit.
import type { SVGProps } from 'react';

export function TextBoldIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      width={24}
      height={24}
      viewBox='0 0 24 24'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
      aria-hidden
      {...props}
    >
      <path
        d='M3 6V5C3 3.89543 3.89543 3 5 3H12M21 6V5C21 3.89543 20.1046 3 19 3H12M12 3V21M14 21H10'
        stroke='currentColor'
        strokeWidth='2'
        strokeLinecap='round'
        strokeLinejoin='round'
      />
    </svg>
  );
}
