// Generated by scripts/generate-icons.mjs from svg/bold/underline.svg. Do not edit.
import type { SVGProps } from 'react';

export function UnderlineBoldIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      width={24}
      height={24}
      viewBox='0 0 24 24'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
      aria-hidden
      {...props}
    >
      <path
        d='M18 21H12H6M6 3V12C6 15.3137 8.68629 18 12 18C15.3137 18 18 15.3137 18 12V3'
        stroke='currentColor'
        strokeWidth='2'
        strokeLinecap='round'
        strokeLinejoin='round'
      />
    </svg>
  );
}
