// Generated by scripts/generate-icons.mjs from svg/linear/water-drop.svg. Do not edit.
import type { SVGProps } from 'react';

export function WaterDropIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      width={24}
      height={24}
      viewBox='0 0 24 24'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
      aria-hidden
      {...props}
    >
      <path
        fillRule='evenodd'
        clipRule='evenodd'
        d='M13.4228 3.1068C12.967 1.73925 11.0326 1.73927 10.5768 3.10681L6.83289 14.3385C6.234 16.1352 6.70161 18.116 8.04077 19.4552L8.46429 19.8787C10.4169 21.8313 13.5827 21.8313 15.5354 19.8787L15.9589 19.4552C17.298 18.116 17.7656 16.1352 17.1667 14.3385L13.4228 3.1068ZM8.73026 14.971L11.9998 5.16229L15.2694 14.971C15.6287 16.049 15.3481 17.2375 14.5446 18.041L14.1211 18.4645C12.9496 19.636 11.0501 19.636 9.8785 18.4645L9.45499 18.041C8.65149 17.2375 8.37092 16.049 8.73026 14.971Z'
        fill='currentColor'
      />
    </svg>
  );
}
